[package]
name = "rtest_user_macros"
version = "0.1.0"
authors = ["jTitor <me@me.me>"]
edition = "2018"
workspace = "../../"
description = "Defines user-facing standard macros for the rtest library."

[dependencies]

[lib]
name = "rtest_user_macros"