[package]
name = "rtest_macros"
version = "0.1.0"
authors = ["jTitor <me@me.me>"]
edition = "2018"
workspace = "../../"

[dependencies]
rtest_impl = { path = "../rtest_impl", version = "*" }

[lib]
name = "rtest_macros"
#Enable custom macro definition
proc-macro = true